### ISSUE TITLE
df only columns

### ISSUE THREAD

**Issue by nim-hrkn** [janssenhenning/aiida-dataframe#2]
I would like to use aiida-dataframe in my porting of crystal structure search package, CrySPY, 
but I have a trouble.  Is it possible to change your code to handle dataframe without any data?
An example, 
<pre>
import pandas as pd
df = pd.DataFrame([], columns=["x","y"])
df
PandasFrameData = DataFactory('dataframe.frame')
framedata = PandasFrameData(df) 
</pre>
causes
AttributeError: 'PandasFrameData' object has no attribute '_df'

**Comment by janssenhenning** [comment]
Thanks for reporting this issue 👍 

I tested this and I get a different error message. 
```
ValueError: Dataset(s) incompatible with Pandas data types, not table, or no datasets found in HDF5 file.
```
For this error message I have prepared a fix in #3. Would it be possible 
for you to clone the branch of this PR and test if this fixes your problem?

**Comment by nim-hrkn** [comment]
Thank you for your quick response. It worked also on my environment, aiida-core 1.6.8 with Python 3.9.13.

**Comment by janssenhenning** [comment]
Thanks for testing. In that case I will prepare a bugfix release of this plugin today

If you have any other questions/problems feel free to open other issues :)
